# Site settings
title: My production site
email: your-email@prod.com
description: > # this means to ignore newlines until "baseurl:"
  This is the production site
baseurl:        "/learnosm-sandbox" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# delay in seconds for displaying the english version of untranslated pages
delay: 30

# Not documented (for pages). See https://github.com/jekyll/jekyll/blob/c2f0b9a7994afcff4a22dbff065ab6dbdcab21da/lib/jekyll/page.rb#L66
# The parameter in _config.yml is permalink but inside ruby code, the class property is permalink_style ;-)
permalink: pretty
# pretty: For page /en/beginer/introduction.xx URL are /en/beginer/introduction/
# else /en/beginer/introduction.html

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: pyrog
repo: learnosm-sandbox
#branch: master
#production_url:  http://pyrog.github.io/learnosm-sandbox
#source_url:      http://github.com/pyrog/learnosm-sandbox
destination:     "./_site"


exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - .travis.yml